import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState, useRef } from "react";
import profilephoto from "../public/images/ProfilePic.png";
import Image from "next/legacy/image";
import BlackSkillsStar from "../public/images/BlackSkillsStar.svg"
import GreigeSkillsStar from "../public/images/GreigeSkillsStar.svg"
import BlackContactStar from "../public/images/BlackContactStar.svg"
import GreigeContactStar from "../public/images/GreigeContactStar.svg"
import BlackStar from "../public/images/BlackStar.svg"
import WhiteStar from "../public/images/WhiteStar.svg"
import Sauced from "../public/images/sauced.jpg"
import UpArrow from "../public/images/Arrow.svg"
import ImageCarousel from "../public/components/carousel";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const projectsRef = useRef(null);
  const skillsRef = useRef(null);
  const aboutRef = useRef(null);
  const contactRef = useRef(null);
  const topRef = useRef(null);

  const handleProjectsClick = () => {
    projectsRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleSkillsClick = () => {
    skillsRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleContactClick = () => {
    contactRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleTopClick = () => {
    topRef.current.scrollIntoView({ behavior: "smooth" });
  };


  return (
    <div ref={topRef} className={`flex flex-col ${darkMode ? "dark bg-black" : ""}`}>
      <Head>
        <title>Tom Robshaw</title>
        <meta name="Tom Robshaw's Portfolio Page" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <main className="bg-#FDF7F0 dark:bg-black">
        <section className="mx-auto max-w-[1380px]">
          <nav className="py-10 mb-6 flex flex-row sm:gap-1 justify-end text-customBlack dark:text-white">
            <ul className="flex items-center gap-10">
              <li>
              <button
                className="border-transparent border-solid border-2 rounded-full py-4 px-8 hover:border-black"
                onClick={handleProjectsClick}
              >
                PROJECTS
              </button>

              </li>
              <li>
                <button
                  className="border-transparent border-solid border-2 rounded-full py-4 px-8 hover:border-black"
                  onClick={handleSkillsClick}>SKILLS</button>
              </li>
              <li>
                <button
                  className="border-transparent border-solid border-2 rounded-full py-4 px-8 hover:border-black"
                  onClick={handleContactClick}
                >
                  ABOUT
                </button>
              </li>
              <li>
                <button
                  className="border-black border-solid border-2 rounded-full py-4 px-8 hover:scale-105"
                  onClick={handleContactClick}
                  >
                  CONTACT
                </button>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="flex flex-row sm:flex-col-reverse md:flex-row lg:flex-row xl:flex-row mb-20 w-full h-[1/2] ml-20">
            <div className="bg-opacity-0 absolute transform -translate-x-20 translate-y-16 z-10 w-[200px]">
              {darkMode ? (
                <Image src={WhiteStar} className="" />
              ) : (
                <Image src={BlackStar} className="" />
              )}
            </div>
            <div className="min-w-[416px] min-h-[620px] max-w-[416px] max-h-[620px] -rotate-12 translate-x-12 hover:scale-105">
              <Image
                src={profilephoto}
              />
            </div>
            <div className="flex flex-col">
              <h1 className="text-8xl mt-10 p-0 tracking-tighter text-black font-medium dark:text-customGreige -translate-x-10 z-10">
                Tom
              </h1>
              <h1 className="text-8xl p-0 ml-12 tracking-tighter text-black font-medium dark:text-customGreige z-10">
                Robshaw
              </h1>
              <h3 className="text-lg py-2 ml-24 text-black dark:text-white">
                JUNIOR SOFTWARE ENGINEER
              </h3>
              <p className="text-sm py-5 ml-24 text-black dark:text-white max-w-xl mx-auto md:text-sm">
              With over a decade of real-world hustle, I'm no ordinary<br></br>junior. Experience in Ruby, React.JS, and C#, I'm the go-<br></br>getter ready to inject ambition into your team and tackle challenges head-on.
              </p>
              <a
                className="btn group flex items-center bg-transparent py-4 px-8 ml-24 text-md dark:border-white border-black border-solid border-2 rounded-full w-fit"
                href="https://drive.google.com/file/d/11vxFI9oY-854bg2c3QWptAl_6VB2G1bX/view?usp=sharing"
                >
                <span className="relative pr-4 pb-1 text-customBlack dark:text-white after:transition-transform after:duration-500 after:ease-out after:absolute after:bottom-0 after:left-0 after:block after:h-[2px] after:w-full after:origin-bottom-right after:scale-x-0 after:bg-black after:content-[''] after:group-hover:origin-bottom-left after:group-hover:scale-x-100">
                  DOWNLOAD RÉSUMÉ
                </span>
                <svg viewBox="0 0 46 16" height="10" width="30" xmlns="http://www.w3.org/2000/svg" id="arrow-horizontal" class="-translate-x-2 fill-slate-700 transition-all duration-300 ease-out group-hover:translate-x-1 group-hover:scale-x-105 group-hover:fill-white">
                  <path transform="translate(30)" d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z" data-name="Path 10" id="Path_10"></path>
                </svg>
              </a>
            </div>
          </div>

        </section>

          <div ref={projectsRef} className="mb-20 w-full mx-auto max-w-[1380px]">
            <h3 className="text-5xl py-1 dark:text-white mb-10">PROJECTS</h3>
            <div className="flex flex-row w-full mb-20 sm:flex-col-reverse md:flex-row lg:flex-row xl:flex-row">
              <div className="w-fit min-w-[400px] mt-12 hover:scale-105 mr-10">
                <Image src={Sauced} />
                </div>
              <div className="flex flex-col w-fit">
                <h3 className="text-3xl py-1 dark:text-white">Sauced</h3>
                <div className="flex flex-row gap-2">
                  <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">C#</h4>
                  <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">REACT.JS</h4>
                  <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">MONGODB</h4>
                  <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">SQL</h4>
                  <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">AZURE</h4>
                </div>
                <p className="mt-4 dark:text-white lg:text-lg xl:text-xl mx-auto" >
                  An exciting new addition to Cooking the books platform launching 2024,
                  built from scratch in small team of 3. This web application allows companies
                  to create, track and manage adverts. With the use of Google APIs
                  for geolocation when targeting adverts along with government ABN APIs to ensure safe
                  company registration and Stripe Payment management integration for ongoing
                  subscriptions and one-time payments. This web app is an in-depth advert management
                  software, giving the ability to track statistics of adverts by storing time-series
                  data using MONGODB, manage users and company information using SQL, complete with
                  an integrated inbox to manage enquiries between users.
                </p>
              </div>
            </div>
              <div className="flex flex-row w-full mb-20 sm:flex-col md:flex-row lg:flex-row xl:flex-row">
                <div className="flex flex-col mr-10 w-fit">
                    <h3 className="text-3xl py-1 dark:text-white">ServoMate</h3>
                    <div className="flex flex-row gap-2">
                      <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">RUBY</h4>
                      <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">JAVASCRIPT</h4>
                      <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">HTML</h4>
                      <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">SQLITE</h4>
                      <h4 className="text-md rounded-full px-4 py-1 bg-customGreige text-white">HEROKU</h4>
                    </div>
                    <p className="mt-4 dark:text-white mb-4 lg:text-lg xl:text-xl mx-auto">
                      A mobile appication to help users track and manage their car maintenance,
                      from service history to vehicle health statuses. Utilising car manufacturers
                      specifications to determine the longevity of vital consumable car parts
                      such as; tyres, brakes, spark plugs etc. The ability to search for local
                      nearby garages and contact them through a live chat to book in that next
                      important service. This project was selected as part of the Le Wagon
                      bootcamp web development, led by myself with two other developers under
                      pressure of an 8-day turnaround. Giving us great insight to real-world
                      problems with use of agile methodologies.
                    </p>
                    <button
                      className="btn group flex items-center bg-transparent py-4 px-8 text-md dark:border-white border-black border-solid border-2 rounded-full w-fit"
                      onClick={() => window.open('https://www.youtube.com/watch?v=A0D4YiNwV-8&t=2044s', '_blank')}
                      >
                      <span className="relative pr-4 pb-1 text-customBlack dark:text-white after:transition-transform after:duration-500 after:ease-out after:absolute after:bottom-0 after:left-0 after:block after:h-[2px] after:w-full after:origin-bottom-right after:scale-x-0 after:bg-black after:content-[''] after:group-hover:origin-bottom-left after:group-hover:scale-x-100">
                        WATCH DEMO
                      </span>
                      <svg viewBox="0 0 46 16" height="10" width="30" xmlns="http://www.w3.org/2000/svg" id="arrow-horizontal" class="-translate-x-2 fill-slate-700 transition-all duration-300 ease-out group-hover:translate-x-1 group-hover:scale-x-105 group-hover:fill-white">
                        <path transform="translate(30)" d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z" data-name="Path 10" id="Path_10"></path>
                      </svg>
                    </button>
                </div>
                <div className="mt-12 w-fit min-w-[400px] max-w-[700px] hover:scale-105">
                    <ImageCarousel
                    content="servoMate"
                    showThumbs={false}
                    showStatus={false}
                    />
                </div>
              </div>
          </div>

          <div ref={skillsRef} className="flex flex-col gap-12 mt-12 w-full h-[1/2] mx-auto max-w-[1380px]">
            <div className="flex items-center justify-end relative">
            <div className="border-t-2 border-solid border-black dark:border-customGreige w-full"></div>
              {darkMode? (
                <Image src={GreigeSkillsStar} className=""/>
              ) : (
                <Image src={BlackSkillsStar} className=""/>
              )}
            </div>
            <div className="flex flex-row">
              <h3 className="text-3xl whitespace-nowrap w-fit mr-4 text-customBlack dark:text-white">Tech Stack</h3>
              <p className="text-customBlack dark:text-white">
              Javascript ✸ C# ✸ React.JS ✸ Ruby ✸ SQL ✸ MongoDB ✸ Azure ✸ Git ✸ Github ✸ Next.JS ✸ CSS ✸ HTML ✸ Sass ✸ Terminal ✸ Figma ✸ Webpack ✸ Heroku ✸ VSCode ✸  Docker ✸ Bootstrap ✸ Tailwind
              </p>
            </div>
            <div className="flex flex-row">
              <h3 className="text-3xl whitespace-nowrap mr-4 text-customBlack dark:text-white">Soft Skills</h3>
              <p className="text-customBlack dark:text-white">
              Analytical Thinking ✸ Critical Analysis ✸ Problem-Solving Abilities ✸ Effective Communication ✸ Adaptability ✸ Time Management Efficiency ✸ Team Collaboration ✸ Leadership Qualities ✸ Empathy ✸ Creativity ✸ Resilience ✸ Attention to Detail              </p>
            </div>
          </div>
      </main>

          <div className="mt-16 mb-16">
            <div className="bg-customBlack py-8 whitespace-nowrap">
              <ul className="w-full">
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
                <li className="box">JUNIOR SOFTWARE ENGINEER ✸</li>
              </ul>
            </div>

            <div className="text-xl py-8 bg-white text-white dark:text-white dark:bg-black whitespace-nowrap">
              <ul className="w-full">
                <li className="box2 whitespace-nowrap w-fit border-2 border-solid border-black rounded-full px-4 py-2 text-black dark:text-white dark:border-white">Back End Developer</li>
                <li className="box2 whitespace-nowrap w-fit border-2 border-solid border-black rounded-full px-4 py-2 ml-4 text-black dark:text-white dark:border-white">Front End Programmer</li>
                <li className="box2 whitespace-nowrap w-fit border-2 border-solid border-black rounded-full px-4 py-2 ml-4 text-black dark:text-white dark:border-white">Full Stack Developer</li>
              </ul>
            </div>
          </div>

          <div className="bg-#FDF7F0 dark:bg-black ">
            <div ref={aboutRef} className="flex flex-row mt-12 w-full h-[1/2] mx-auto max-w-[1380px]">
              <h3 className="text-5xl py-1 dark:text-white w-1/2">ABOUT</h3>
              <p className="w-1/2 text-customBlack dark:text-white mb-20">
              Hello! Originally from Yorkshire, UK, I'm now an Aussie citizen based in
              Melbourne. With over a decade in manufacturing, I've honed my skills
              programming machines and crafting code for robots across various
              industries, from defence forces to pharmaceuticals. Inspired by the
              allure of innovation, I made a bold leap into software development,
              transitioning seamlessly from hardware to software. Driven by a
              relentless passion for problem-solving and a thirst for learning, I'm
              excited to leverage my diverse experiences to make a meaningful
              impact in Melbourne's dynamic tech landscape.
              </p>
            </div>
          </div>

          <div ref={contactRef} className="flex flex-col bg-black dark:bg-customGreige rounded-t-large w-full">
            <div className="flex flex-row mt-12 w-full items-start mx-auto max-w-[1380px]">
              {darkMode? (
                <Image src={BlackContactStar} className=""/>
                ) : (
                <Image src={GreigeContactStar} className=""/>
              )}
              <div className="ml-12">
                <h2 className="text-8xl mt-10 p-0 tracking-tighter text-white font-medium dark:text-black">Let's</h2>
                <h2 className="text-8xl ml-16 mb-12 p-0 tracking-tighter text-white font-medium dark:text-black">work together</h2>
                <p className="text-white font-medium dark:text-black mb-2 ml-16">Say hello!👋</p>
                <h3 className="text-4xl text-white font-medium dark:text-black mb-20 ml-16">t.a.robshaw@gmail.com</h3>
              </div>
            </div>
            <div className="flex flex-row justify-between mb-20 w-full max-w-[1380px] mx-auto">
              <p className="text-white font-medium dark:text-black">✸TOMROBSHAW.COM.AU</p>
              <div className="flex flex-row gap-8">
                <button className="text-white font-medium dark:text-black"
                  onClick={() => window.open('https://www.linkedin.com/in/tom-robshaw/', '_blank')}
                >
                  LINKEDIN ↗
                </button>
                <button className="text-white font-medium dark:text-black"
                  onClick={() => window.open('https://github.com/TomRobshaw', '_blank')}
                >
                  GITHUB ↗
                </button>
                <button onClick={handleTopClick} className="bg-customWhite rounded-full px-6 py-5">
                  <Image src={UpArrow} />
                </button>
              </div>
            </div>

          </div>
    </div>
  );
}
