import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profilephotosq from "../public/profilephotosq.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/legacy/image";
import comingsoon from "../public/comingsoon.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="Tom Robshaw's Portfolio Page" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-orange-100 px-10 dark:bg-slate-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-6 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Developer Tom</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-orange-500 text- to-orange-600 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/101BDGA3PKMWqK6W7TIIy29f0zNGrO6B8/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-2">
            <h2 className="text-5xl py-2 text-orange-500 font-medium dark:text-orange-700 md:text-6xl">
              Tom Robshaw
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As an extroverted developer, I thrive in collaborative environments and bring a contagious energy to any team.
              Let's build something great together!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profilephotosq} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Ethos</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as developer, I've worked on multiple
              projects with a strong user experience mindset as the main focus - I figure
              there's no point building amazing apps if people can't use them... right?
              I enjoy building applications, software and websites with purpose. Making
              people's lives easier or safer with the use of technology is the future we
              need right now. Got something in mind? Let's build!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Languages
              </h3>
              <p className="py-2">
                Creating a flexible vocabularly, eager to learn more!
              </p>
              <h4 className="py-4 text-teal-600">Code I've used</h4>
              <p className="text-gray-800 py-1">HMTL</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Ruby</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Next.JS</p>
              <p className="text-gray-800 py-1">C#</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Toolkit
              </h3>
              <p className="py-2">
                From agile work management to design tools, let's get efficient!
              </p>
              <h4 className="py-4 text-teal-600">Tools I've used</h4>
              <p className="text-gray-800 py-1">JIRA</p>
              <p className="text-gray-800 py-1">Trello</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Miro</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">VSCode</p>
              <p className="text-gray-800 py-1">Visual Studio</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Capablilities</h3>
              <p className="py-2">
                Whether it's working solo or in a team,
                I'm always keen to give thing's a go.
              </p>
              <h4 className="py-4 text-teal-600">I've worked on</h4>
              <p className="text-gray-800 py-1">FrontEnd</p>
              <p className="text-gray-800 py-1">BackEnd</p>
              <p className="text-gray-800 py-1">Database Schema</p>
              <p className="text-gray-800 py-1">Cloud Services</p>
              <p className="text-gray-800 py-1">User Story</p>
              <p className="text-gray-800 py-1">User Journey</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a developer I've been lucky to work on
              these following projects:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={comingsoon}
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
